name: kandinsky
description: A tiny color library. Create (dymanic and fixed) radial and linear gradients, convert rgb, hex, hsl and css colors.
version: 1.0.0
homepage: https://github.com/renanborgez/kandinsky-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7
