name: kandinsky
description: A tiny color library. Create (dymanic and fixed) radial and linear gradients, convert rgb, hex, hue, hsl and css colors.
version: 1.0.2
homepage: https://github.com/renanborgez/kandinsky-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7
  test_coverage: ^0.4.2

dependency_overrides:
  meta: 1.6.0
